server:
  port: 0

spring:
  config:
    import: optional:http://localhost:8012
  application:
    name: USERS-WS
  datasource:
    url: jdbc:mysql://localhost:3306/e-commercy
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka

gateway:
#  ip: 192.168.1.6
  ip: 10.164.178.61
token:
  expiration_time: 3600000
  secret: 123481203958asdfmasdfzocixubbozixusndfn399129djlkvclzvjksjajdfj